/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestCal */

#ifndef _Included_TestCal
#define _Included_TestCal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestCal
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_TestCal_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     TestCal
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_TestCal_sub
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
